### ISSUE TITLE
Server down?

### ISSUE THREAD

**Issue by Cj-Malone** [scripting/xmlViewer#1]
I suspect there is an issue with your server? I'm just getting a 500 "connect ECONNREFUSED" error.

`curl -v "http://xmlviewer.scripting.com/?url=http://scripting.com/rss.xml"`
```
GET /?url=http://scripting.com/rss.xml HTTP/1.1
> Host: xmlviewer.scripting.com
> User-Agent: curl/7.54.1
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain
< Date: Fri, 28 Jul 2017 20:52:16 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
connect ECONNREFUSED
```

BTW I was using this as a browser bookmarklet on my mobile devices and tablets, it really did help.

**Comment by scripting** [comment]
Thanks for the report. The xmlviewer app was down, it's now back up. Operator error. ;-)

http://xmlviewer.scripting.com/?url=http://scripting.com/rss.xml
